
import pandas as pd
import quandl
import math
import numpy as np
from statistics import mean
from sklearn import preprocessing, cross_validation, svm
from sklearn.linear_model import LinearRegression
import datetime
import matplotlib.pyplot as plt
from matplotlib import style
import pickle
import os
import random

style.use('ggplot')

# Basic LinearRegression Using random data generated by method

def RegressionUsingSKLearn():

    df = quandl.get('WIKI/GOOGL', api_key='6yDydmxh-cSGy9vzbs74')

    impdf = df[['Adj. Open','Adj. High','Adj. Low','Adj. Close','Adj. Volume']]

    impdf['HL_PCT'] = (impdf['Adj. High'] - impdf['Adj. Close']) / impdf['Adj. Close'] * 100.0

    impdf['PCT_Change'] = (impdf['Adj. Close'] - impdf['Adj. Open']) / impdf['Adj. Open'] * 100.0

    impdf = impdf[['Adj. Close','HL_PCT','PCT_Change','Adj. Volume']]

    forecastCol = 'Adj. Close'

    impdf.fillna(-99999, inplace = True)

    forecastOut = int(math.ceil(0.01*len(impdf)))

    impdf['label'] = impdf[forecastCol].shift(-forecastOut)

    X = np.array(impdf.drop(['label'],1))
    X = preprocessing.scale(X)
    X = X[:-forecastOut]
    type(X)
    len(X)
    XLately = X[-forecastOut:]

    impdf.dropna(inplace=True)
    y = np.array(impdf['label'])
    type(y)
    len(y)
    # X = X[: -forecastOut + 1]
    # find min length and use that much data
    n = min(len(X), len(y))
    # impdf.dropna(inplace=True)

    X_train, X_test, y_train, y_test = cross_validation.train_test_split(X[:n], y[:n], test_size = 0.2)

    clf = LinearRegression(n_jobs=-1)
    # switch algo
    # clf = svm.SVR()

    clf.fit(X_train, y_train)

    #  Save trained classifier in pickle

    # cwd = os.getcwd()
    # os.chdir(os.getcwd()+'\\Regression')

    with open('LinearRegression.pickle','wb') as f:
        pickle.dump(clf, f)

    #  load trained classifier again
    pickleIn = open('LinearRegression.pickle','rb')
    clf = pickle.load(pickleIn)

    accu = clf.score(X_train,y_train)

    forecastSet = clf.predict(XLately)
    impdf['Forecast'] = np.nan

    lastDate = df.iloc[-1].name
    lastUnix = lastDate.timestamp()
    oneDay = 86400
    nextUnix = lastUnix + oneDay

    for i in forecastSet:
        nextDate = datetime.datetime.fromtimestamp(nextUnix)
        nextUnix += oneDay
        impdf.loc[nextDate] = [np.nan for _ in range(len(impdf.columns)-1)] + [i]

    print(forecastSet, accu, forecastOut)

    # issue solved
    impdf['Adj. Close'].plot()
    impdf['Forecast'].plot()
    plt.legend(loc=4)
    plt.xlabel('Date')
    plt.ylabel('Price')

    return 0;


def bestFitSlope(xs, ys):
    # formula
    m = (((mean(xs) * mean(ys)) - mean(xs * ys)) /
            ((mean(xs)**2) - (mean(xs**2))))
    return m

def bestIntercept(xs, ys, m):
    # formula
    b = mean(ys) - m * mean(xs)
    return b

def predict(m, x, b):
    return (m * x) + b;

def squareError(ysOrig,ysLine):
    return sum((ysLine - ysOrig)**2)

def coefOFDetermination(ysOrig,ysLine):
    # ysOrig,ysLine = ys,regline
    # formula
    #  r^2 = 1 - SE(y^)/SE(y-)
    yMeanLine = [mean(ysOrig) for y in ysOrig]
    squaredErrorReg = squareError(ysOrig,ysLine)
    squaredErroryMean = squareError(ysOrig,yMeanLine)
    return 1 - (squaredErrorReg / squaredErroryMean )

def createdataSet(hm,var,step=2,corr=False):
    val = 1
    ys=[]
    for i in range(hm):
        y = val + random.randrange(-var,var)
        ys.append(y)

        if corr and corr == 'pos':
            val+=step
        elif corr and corr == 'neg':
            val-=step
    xs = [i for i in range(len(ys))]

    return np.array(xs, dtype=np.float64), np.array(ys, dtype=np.float64)

def ProgrameBestFitSlope():

    xs = np.array([1,2,3,4,5,6])
    ys = np.array([5,4,6,5,6,7])

    xs, ys = createdataSet(40,10,2,corr=False)


    m = bestFitSlope(xs, ys)
    b = bestIntercept(xs, ys, m)

    regline = [(m*x)+b for x in xs]

    style.use('fivethirtyeight')

    predictfor = 8

    predicValue = predict(m, predictfor, b)

    rSquared = coefOFDetermination(ys,regline)
    print(rSquared)

    plt.plot(xs,regline)
    plt.scatter(xs,ys, color = 'b')
    plt.scatter(predictfor,predicValue, s=100, color = 'r')
    # plt.scatter(xs,regline)
    plt.show()

    return 0;



def main():

    RegressionUsingSKLearn();
    ProgrameBestFitSlope();

    return 0;


if __name__ == '__main__':
    main()
